#!/bin/bash
# Quick Deploy Helper Script

echo "🚀 VERTIKAL DEPLOYMENT HELPER"
echo "=============================="
echo ""
echo "Choose deployment method:"
echo ""
echo "1. GitHub Desktop Push (Recommended - Auto-deploys)"
echo "   → Open GitHub Desktop"
echo "   → Click 'Push origin'"
echo "   → Monitor: https://github.com/AlphaJRR/vertikal/actions"
echo ""
echo "2. Cloudflare Direct Upload (No Git Required)"
echo "   → Go to: https://dash.cloudflare.com"
echo "   → Pages → Upload assets"
echo "   → Upload folders from:"
echo "     • public/ → vertikalapp"
echo "     • public/investors/ → investors-vertikalapp"
echo "     • public/creators/ → creators-vertikalapp"
echo "     • public/networks/ → networks-vertikalapp"
echo ""
echo "3. Install Wrangler CLI (Fast CLI Method)"
echo "   → Run: npm install -g wrangler"
echo "   → Then: wrangler login"
echo "   → Then: wrangler pages deploy"
echo ""
echo "Current Status:"
echo "  ✅ 33 commits ready"
echo "  ✅ All 4 sites ready"
echo "  ✅ Workflows configured"
echo ""
echo "RECOMMENDED: Use GitHub Desktop to push (fastest)"
