// ============================================================
// AVA Event Photo Delivery — TypeScript types.
// Mirrors ava-event-delivery-migration.sql (004) + 005_event_triggers.sql.
//
// PAYMENT MODEL: OFFLINE ONLY.
// No Stripe, no IAP, no in-app purchase of any kind.
// orders/order_items/print_jobs/event_products/discount_codes exist in DB
// but are UNUSED in v1 — no app code references them.
// Access to a gallery is granted solely by entering a valid redeem_code.
// ============================================================

// ─── events ──────────────────────────────────────────────────────────────────

export type EventStatus = 'draft' | 'active' | 'expired' | 'archived';

export interface AVAEvent {
  id:              string;
  photographer_id: string;
  name:            string;
  event_date:      string | null;
  cover_image_url: string | null;
  access_code:     string;    // photographer reference; NOT used for gallery access
  qr_token:        string;    // encodes into QR; used for attribution + event discovery
  event_type:      string;
  status:          EventStatus;
  expires_at:      string | null;
  created_at:      string;
  /** When true, POS must collect phone OR email (manual outreach only). */
  require_attendee_contact: boolean;
  /** Shown on guest welcome screen when no photos assigned yet. */
  welcome_message: string | null;
}

// ─── event_photos ─────────────────────────────────────────────────────────────

export type PhotoSource = 'sony' | 'manual' | 'batch';
export type EventMediaKind = 'photo' | 'video';

export interface EventPhoto {
  id:           string;
  event_id:     string;
  storage_path: string;   // key in event-originals bucket
  thumb_path:   string;   // key in event-previews bucket (set by process-photo fn)
  filename:     string | null;
  source:       PhotoSource;
  media_kind:   EventMediaKind;
  exif:         Record<string, unknown> | null;
  uploaded_at:  string;
}

// ─── attendees ────────────────────────────────────────────────────────────────

export interface Attendee {
  id:               string;
  event_id:         string;
  user_id:          string | null;   // set when buyer redeems their code
  first_name:       string | null;
  last_name:        string | null;
  email:            string | null;   // optional; never gates gallery
  phone:            string | null;   // OPTIONAL — data minimization
  is_adult:         boolean;
  marketing_opt_in: boolean;
  photo_consent_at: string | null;
  terms_accepted_at: string | null;
  deleted_at:       string | null;   // soft-delete
  redeem_code:      string | null;   // auto-generated by 005 trigger; shown to buyer
  created_at:       string;
  /** Offline POS: how many digital photos the buyer paid for (not in-app payment). */
  photos_purchased: number;
}

export function attendeeFullName(a: Pick<Attendee, 'first_name' | 'last_name' | 'email'>): string {
  return [a.first_name, a.last_name].filter(Boolean).join(' ') || a.email || 'Unknown';
}

// ─── attendee_interests ───────────────────────────────────────────────────────

export type AttendeeInterest =
  | 'family_portraits'
  | 'graduation'
  | 'sports'
  | 'video_production';

export const INTEREST_LABELS: Record<AttendeeInterest, string> = {
  family_portraits: 'Family portraits',
  graduation:       'Graduation',
  sports:           'Sports',
  video_production: 'Video production',
};

// ─── photo_assignments ────────────────────────────────────────────────────────

export interface PhotoAssignment {
  id:          string;
  photo_id:    string;
  attendee_id: string;
  assigned_at: string;
}

// ─── consent_log ──────────────────────────────────────────────────────────────

export type ConsentType = 'photo_release' | 'marketing' | 'terms' | 'age_confirm';

export interface ConsentLog {
  id:           string;
  attendee_id:  string | null;
  consent_type: ConsentType;
  granted:      boolean;
  granted_at:   string;
}

// ─── install_events ───────────────────────────────────────────────────────────

export interface InstallEvent {
  id:         string;
  event_id:   string | null;
  type:       'qr_scan' | 'install' | 'account_created';
  device_id:  string | null;
  created_at: string;
}

// ─── Upload queue item (AsyncStorage persisted) ───────────────────────────────

export type QueueItemStatus = 'pending' | 'uploading' | 'done' | 'failed';

export interface UploadQueueItem {
  id:          string;
  eventId:     string;
  localUri:    string;
  storagePath: string;    // {eventId}/{id}/original in event-originals bucket
  filename:    string | null;
  mediaKind:   EventMediaKind;
  retries:     number;
  status:      QueueItemStatus;
  addedAt:     number;
  /** Set when an upload attempt fails — shown in operator UI. */
  lastError?:  string;
}

// ─── Redeem RPC response ──────────────────────────────────────────────────────

export interface RedeemResult {
  attendee_id: string;
  event_id:    string;
  event_name:  string;
}

// ─── Dashboard aggregate ──────────────────────────────────────────────────────

export interface EventDashboard {
  event:          AVAEvent;
  totalPhotos:    number;
  totalAttendees: number;
  installs:       number;    // install_events count
  delivered:      number;    // attendees with ≥1 assigned photo
  codesRedeemed:  number;    // attendees with user_id IS NOT NULL
  leads:          number;    // attendees with email
  optIns:         number;    // marketing_opt_in = true
  releaseSigned:  number;    // photo_consent_at IS NOT NULL
}
