import { StyleSheet } from "react-native";
import { brandColors, brandFonts, filmAccents } from "../../constants/brand";

export const creatorTrainingStyles = StyleSheet.create({
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    marginBottom: 16,
  },
  sectionEyebrow: {
    fontFamily: brandFonts.mono,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: brandColors.alphaRed,
    marginBottom: 6,
  },
  sectionTitle: {
    fontFamily: brandFonts.display,
    fontSize: 28,
    color: brandColors.pureWhite,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: brandColors.borderGray,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: {
    borderBottomColor: brandColors.alphaRed,
  },
  tabLabel: {
    fontFamily: brandFonts.mono,
    fontSize: 9,
    letterSpacing: 1.35,
    textTransform: "uppercase",
    color: brandColors.inactiveTab,
  },
  tabLabelActive: {
    color: brandColors.pureWhite,
  },
  categoryPanel: {
    backgroundColor: brandColors.deepBlack,
    borderRadius: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  categoryHeaderLeft: {
    flex: 1,
  },
  categoryEyebrow: {
    fontFamily: brandFonts.mono,
    fontSize: 9,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: brandColors.alphaRed,
    marginBottom: 4,
  },
  categoryTitle: {
    fontFamily: brandFonts.display,
    fontSize: 40,
    color: brandColors.pureWhite,
    textTransform: "uppercase",
    lineHeight: 42,
  },
  categoryDivider: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: brandColors.borderGray,
  },
  dividerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: brandColors.alphaRed,
  },
  lessonList: {
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  lessonCard: {
    backgroundColor: brandColors.graphite,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  lessonBadge: {
    backgroundColor: brandColors.alphaRed,
    minWidth: 32,
    height: 32,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  lessonBadgeText: {
    fontFamily: brandFonts.display,
    fontSize: 16,
    color: brandColors.pureWhite,
  },
  lessonBody: {
    flex: 1,
  },
  lessonTitle: {
    fontFamily: brandFonts.display,
    fontSize: 20,
    color: brandColors.pureWhite,
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  lessonDesc: {
    fontFamily: brandFonts.body,
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.subtleText,
  },
  imagePlaceholder: {
    width: "100%",
    height: 120,
    backgroundColor: brandColors.graphite,
    borderRadius: 8,
    marginTop: 10,
  },
  expandedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: brandColors.avaBlack,
    zIndex: 100,
  },
  expandedScroll: {
    flex: 1,
  },
  expandedContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  backLink: {
    fontFamily: brandFonts.bodyMedium,
    fontSize: 14,
    color: brandColors.alphaRed,
    marginBottom: 16,
  },
  expandedTitle: {
    fontFamily: brandFonts.display,
    fontSize: 32,
    color: brandColors.pureWhite,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 20,
  },
  presentationBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: brandColors.alphaRed,
    backgroundColor: "rgba(232, 0, 10, 0.1)",
  },
  presentationBtnText: {
    flex: 1,
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: brandColors.pureWhite,
  },
  lessonSectionEyebrow: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: brandColors.alphaRed,
    marginBottom: 8,
  },
  expandedDescription: {
    fontFamily: brandFonts.body,
    fontSize: 15,
    lineHeight: 22,
    color: brandColors.secondaryText,
    marginBottom: 24,
  },
  guideText: {
    fontFamily: brandFonts.body,
    fontSize: 14,
    lineHeight: 21,
    color: brandColors.subtleText,
    marginBottom: 24,
  },
  guideImageWrap: {
    marginBottom: 24,
  },
  guideImage: {
    width: "100%",
    height: 180,
    borderRadius: 8,
    marginBottom: 8,
  },
  guideImagePlaceholder: {
    backgroundColor: "#111111",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  guideImageCaption: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: brandColors.mutedText,
  },
  guideImagePlaceholderLabel: {
    fontFamily: brandFonts.body,
    fontSize: 12,
    lineHeight: 18,
    color: brandColors.mutedText,
    textAlign: "center",
  },
  guidedLinkText: {
    color: brandColors.alphaRed,
    textDecorationLine: "underline",
  },
  keyRuleBlock: {
    borderLeftWidth: 3,
    borderLeftColor: brandColors.alphaRed,
    backgroundColor: brandColors.graphite,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  keyRuleLabel: {
    fontFamily: brandFonts.display,
    fontSize: 18,
    color: brandColors.alphaRed,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  keyRuleText: {
    fontFamily: brandFonts.bodySemiBold,
    fontSize: 15,
    lineHeight: 22,
    color: brandColors.pureWhite,
  },
  howToHeader: {
    fontFamily: brandFonts.display,
    fontSize: 22,
    color: brandColors.alphaRed,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 14,
  },
  proTipBlock: {
    borderLeftWidth: 3,
    borderLeftColor: filmAccents.teal,
    paddingLeft: 14,
    marginTop: 8,
    marginBottom: 20,
  },
  proTipText: {
    fontFamily: brandFonts.body,
    fontSize: 14,
    lineHeight: 21,
    color: brandColors.secondaryText,
  },
  commonMistakeBlock: {
    paddingLeft: 14,
    borderLeftWidth: 3,
    borderLeftColor: brandColors.borderGray,
    marginBottom: 8,
  },
  commonMistakeEyebrow: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: brandColors.mutedText,
    marginBottom: 8,
  },
  commonMistakeText: {
    fontFamily: brandFonts.body,
    fontSize: 14,
    lineHeight: 21,
    color: brandColors.mutedText,
  },
  stepRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  stepNum: {
    fontFamily: brandFonts.display,
    fontSize: 18,
    color: brandColors.alphaRed,
    width: 24,
  },
  stepText: {
    flex: 1,
    fontFamily: brandFonts.body,
    fontSize: 14,
    lineHeight: 21,
    color: brandColors.secondaryText,
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 24,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    backgroundColor: brandColors.graphite,
  },
  saveBtnActive: {
    borderColor: brandColors.alphaRed,
    backgroundColor: "rgba(232, 0, 10, 0.12)",
  },
  saveBtnText: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: brandColors.pureWhite,
  },
});
