import { StyleSheet } from "react-native";
import { brandColors, brandFonts, filmAccents } from "../../constants/brand";

export const AMBER = filmAccents.yellow;

export const rateCalculatorStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: brandColors.avaBlack },
  content: { paddingHorizontal: 20, paddingBottom: 32 },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 8,
  },
  backTxt: {
    fontFamily: brandFonts.bodySemiBold,
    color: brandColors.alphaRed,
    fontSize: 15,
  },
  header: { marginBottom: 20 },
  eyebrow: {
    fontFamily: brandFonts.mono,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: brandColors.alphaRed,
    marginBottom: 6,
  },
  title: {
    fontFamily: brandFonts.display,
    fontSize: 32,
    color: brandColors.pureWhite,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  subtitle: {
    fontFamily: brandFonts.body,
    fontSize: 13,
    lineHeight: 19,
    color: brandColors.subtleText,
  },
  stepRow: {
    flexDirection: "row",
    marginBottom: 20,
    gap: 6,
  },
  stepDot: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: brandColors.borderGray,
  },
  stepDotActive: {
    backgroundColor: brandColors.alphaRed,
  },
  stepLabels: {
    flexDirection: "row",
    marginTop: -14,
    marginBottom: 16,
  },
  stepLabel: {
    flex: 1,
    fontFamily: brandFonts.mono,
    fontSize: 8,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: brandColors.inactiveTab,
    textAlign: "center",
  },
  stepLabelActive: {
    color: brandColors.pureWhite,
  },
  card: {
    backgroundColor: brandColors.graphite,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  cardTitle: {
    fontFamily: brandFonts.bodySemiBold,
    fontSize: 15,
    color: brandColors.pureWhite,
    marginBottom: 4,
  },
  cardHint: {
    fontFamily: brandFonts.body,
    fontSize: 12,
    color: brandColors.subtleText,
    marginBottom: 12,
    lineHeight: 17,
  },
  label: {
    fontFamily: brandFonts.mono,
    fontSize: 9,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: brandColors.subtleText,
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    backgroundColor: brandColors.deepBlack,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    color: brandColors.pureWhite,
    fontFamily: brandFonts.body,
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 4,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: brandColors.deepBlack,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
  },
  chipActive: {
    borderColor: brandColors.alphaRed,
    backgroundColor: "rgba(232,0,10,0.12)",
  },
  chipTxt: {
    fontFamily: brandFonts.mono,
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: brandColors.subtleText,
  },
  chipTxtActive: {
    color: brandColors.pureWhite,
  },
  skillCard: {
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    backgroundColor: brandColors.deepBlack,
    marginBottom: 8,
  },
  skillCardActive: {
    borderColor: brandColors.alphaRed,
    backgroundColor: "rgba(232,0,10,0.08)",
  },
  skillLabel: {
    fontFamily: brandFonts.bodySemiBold,
    fontSize: 15,
    color: brandColors.pureWhite,
  },
  skillRate: {
    fontFamily: brandFonts.mono,
    fontSize: 11,
    color: brandColors.alphaRed,
    marginTop: 2,
  },
  skillDesc: {
    fontFamily: brandFonts.body,
    fontSize: 12,
    color: brandColors.subtleText,
    marginTop: 4,
  },
  lineItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: brandColors.borderGray,
  },
  lineItemZero: {
    backgroundColor: "rgba(255,190,11,0.08)",
    marginHorizontal: -16,
    paddingHorizontal: 16,
    borderLeftWidth: 3,
    borderLeftColor: AMBER,
  },
  lineItemLabel: {
    fontFamily: brandFonts.body,
    fontSize: 14,
    color: brandColors.secondaryText,
    flex: 1,
    paddingRight: 8,
  },
  lineItemAmount: {
    fontFamily: brandFonts.bodySemiBold,
    fontSize: 14,
    color: brandColors.pureWhite,
    minWidth: 72,
    textAlign: "right",
  },
  lineItemAmountZero: {
    color: AMBER,
  },
  gearRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  gearInput: {
    flex: 1,
    backgroundColor: brandColors.deepBlack,
    borderWidth: 1,
    borderColor: brandColors.borderGray,
    color: brandColors.pureWhite,
    fontFamily: brandFonts.body,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
  },
  quotedTotal: {
    fontFamily: brandFonts.display,
    fontSize: 48,
    color: brandColors.alphaRed,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 4,
  },
  quotedLabel: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: brandColors.subtleText,
    marginBottom: 4,
  },
  navRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  btnPrimary: {
    flex: 1,
    backgroundColor: brandColors.alphaRed,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  btnPrimaryTxt: {
    fontFamily: brandFonts.display,
    fontSize: 16,
    color: brandColors.pureWhite,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  btnSecondary: {
    flex: 1,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: brandColors.borderGrayLight,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  btnSecondaryTxt: {
    fontFamily: brandFonts.mono,
    fontSize: 10,
    color: brandColors.secondaryText,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  btnProLocked: {
    opacity: 0.55,
  },
  proBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
  },
  proBadgeTxt: {
    fontFamily: brandFonts.mono,
    fontSize: 9,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: brandColors.subtleText,
  },
  mileageNote: {
    fontFamily: brandFonts.body,
    fontSize: 11,
    color: brandColors.subtleText,
    fontStyle: "italic",
    marginTop: 4,
  },
});
