import { StyleSheet } from "react-native";

export const toolkitStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0a0a0a" },
  content: { paddingHorizontal: 20, paddingBottom: 32 },
  header: { marginBottom: 20 },
  backBtn: { marginBottom: 12 },
  backTxt: { color: "#00d4ff", fontSize: 15, fontWeight: "600" },
  title: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  subtitle: { color: "#888", fontSize: 14, lineHeight: 20 },
  menuCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 16,
    marginBottom: 10,
  },
  menuIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  menuTitle: { color: "#fff", fontSize: 16, fontWeight: "700" },
  menuDesc: { color: "#888", fontSize: 12, marginTop: 4, lineHeight: 17 },
  section: { marginTop: 8, marginBottom: 16 },
  sectionTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "rgba(0,0,0,0.4)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 10,
  },
  textarea: {
    backgroundColor: "rgba(0,0,0,0.4)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 10,
    minHeight: 88,
    textAlignVertical: "top",
  },
  btn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 8,
  },
  btnPrimary: { backgroundColor: "#00d4ff" },
  btnSecondary: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  btnDanger: { backgroundColor: "rgba(255,0,110,0.2)" },
  btnTxtPrimary: { color: "#000", fontWeight: "700", fontSize: 15 },
  btnTxtSecondary: { color: "#fff", fontWeight: "600", fontSize: 14 },
  btnTxtDanger: { color: "#ff006e", fontWeight: "600", fontSize: 14 },
  card: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 16,
    marginBottom: 12,
  },
  cardTitle: { color: "#fff", fontSize: 16, fontWeight: "700", marginBottom: 6 },
  cardBody: { color: "#aaa", fontSize: 13, lineHeight: 19 },
  tag: {
    color: "#00d4ff",
    fontSize: 11,
    fontWeight: "600",
    backgroundColor: "rgba(0,212,255,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    overflow: "hidden",
    marginRight: 6,
    marginBottom: 6,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  rowLabel: { color: "#888", fontSize: 13, textTransform: "capitalize" },
  rowValue: { color: "#fff", fontSize: 13, fontWeight: "600", flex: 1, textAlign: "right" },
  listItem: { color: "#ccc", fontSize: 14, lineHeight: 22, marginBottom: 6 },
  placeholder: { color: "#bbb", fontSize: 14, lineHeight: 22, marginBottom: 10 },
  actionsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
});
