/**
 * Create event — photographer.
 * Required fields: name + access_code.
 * access_code is a photographer reference label (e.g. event abbreviation).
 * Attendees unlock galleries with individual per-buyer redeem_codes, NOT access_code.
 * qr_token is auto-generated by the DB (encode(gen_random_bytes(12),'hex')).
 */

import React, { useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';

import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { brandColors, brandFonts } from '@/constants/theme';
import { useMyEvents } from '@/hooks/useEvents';
import { useOperatorGuard } from '@/hooks/useOperatorGuard';

export default function CreateEventScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { create } = useMyEvents();
  const { isOperator, loading: guardLoading } = useOperatorGuard();

  const [name,      setName]      = useState('');
  const [date,      setDate]      = useState('');
  const [eventType, setEventType] = useState('reunion');
  const [busy,      setBusy]      = useState(false);
  const [error,     setError]     = useState<string | null>(null);

  const EVENT_TYPES = ['reunion','wedding','corporate','sports','graduation','other'];

  // Guard renders a spinner while loading; redirects non-operators via useEffect
  if (guardLoading || !isOperator) {
    return (
      <View style={{ flex: 1, backgroundColor: '#0a0a0a', alignItems: 'center', justifyContent: 'center' }}>
        <ActivityIndicator color="#00BFFF" />
      </View>
    );
  }

  const handleCreate = async () => {
    if (!name.trim()) { setError('Event name is required.'); return; }

    let eventDate: string | undefined;
    if (date.trim()) {
      const d = new Date(date.trim());
      if (isNaN(d.getTime())) { setError('Enter date as YYYY-MM-DD (e.g. 2026-08-15).'); return; }
      eventDate = date.trim();
    }

    setBusy(true);
    setError(null);
    try {
      const ev = await create({
        name:        name.trim(),
        event_date:  eventDate,
        access_code: Math.random().toString(36).slice(2, 8).toUpperCase(),
        event_type:  eventType,
      });

      if (!ev) {
        // Surface RLS rejection cleanly — don't let a non-operator see a cryptic error
        setError('Could not create event. Your account may not have operator access. Contact support.');
        return;
      }
      router.replace(`/events/${ev.id}` as never);
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={{ flex: 1, backgroundColor: '#0a0a0a' }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView
        contentContainerStyle={[
          styles.container,
          { paddingTop: insets.top + 16, paddingBottom: insets.bottom + 32 },
        ]}
        keyboardShouldPersistTaps="handled"
      >
        <Pressable onPress={() => router.back()} hitSlop={12} style={styles.backRow}>
          <Ionicons name="chevron-back" size={22} color={brandColors.alphaRed} />
          <Text style={styles.backText}>Events</Text>
        </Pressable>

        <Text style={styles.title}>New Event</Text>
        <Text style={styles.subtitle}>
          Create an event to generate a QR code and start delivering photos.
        </Text>

        <Field label="Event name *">
          <TextInput
            value={name} onChangeText={setName}
            placeholder="Johnson Family Reunion '26"
            placeholderTextColor={brandColors.mutedText}
            style={styles.input} editable={!busy} autoFocus
          />
        </Field>

        <Field label="Date (optional)">
          <TextInput
            value={date} onChangeText={setDate}
            placeholder="2026-08-15"
            placeholderTextColor={brandColors.mutedText}
            keyboardType="numbers-and-punctuation"
            style={styles.input} editable={!busy}
          />
        </Field>

        <Field label="Event type">
          <View style={styles.typeRow}>
            {EVENT_TYPES.map(t => (
              <Pressable
                key={t}
                style={[styles.typePill, eventType === t && styles.typePillActive]}
                onPress={() => setEventType(t)}
              >
                <Text style={[styles.typePillText, eventType === t && styles.typePillTextActive]}>
                  {t.charAt(0).toUpperCase() + t.slice(1)}
                </Text>
              </Pressable>
            ))}
          </View>
        </Field>

        {error ? <Text style={styles.error}>{error}</Text> : null}

        <Pressable
          style={[styles.btn, busy && styles.btnDisabled]}
          onPress={() => void handleCreate()}
          disabled={busy}
        >
          {busy ? (
            <ActivityIndicator color="#000" />
          ) : (
            <View style={styles.btnInner}>
              <Ionicons name="qr-code-outline" size={18} color="#000" />
              <Text style={styles.btnText}>Create event + get QR</Text>
            </View>
          )}
        </Pressable>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <View style={{ gap: 6, marginTop: 16 }}>
      <Text style={styles.label}>{label}</Text>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  container:  { paddingHorizontal: 24, gap: 0 },
  backRow:    { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 24 },
  backText:   { fontFamily: brandFonts.bodyMedium, fontSize: 15, color: brandColors.alphaRed },
  title:      { fontFamily: brandFonts.display, fontSize: 32, color: '#fff', textTransform: 'uppercase' },
  subtitle:   { fontFamily: brandFonts.body, fontSize: 14, lineHeight: 20, color: brandColors.subtleText, marginTop: 8, marginBottom: 8 },
  label:      { fontFamily: brandFonts.mono, fontSize: 10, letterSpacing: 1.5, textTransform: 'uppercase', color: brandColors.mutedText },
  input:      {
    fontFamily: brandFonts.body, fontSize: 16, color: '#fff',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 10, paddingHorizontal: 14, paddingVertical: 14,
  },
  codeInput:  { letterSpacing: 4, fontSize: 18, fontFamily: brandFonts.mono },
  fieldHint:  { fontFamily: brandFonts.body, fontSize: 11, color: brandColors.mutedText },
  typeRow:    { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  typePill:   {
    paddingVertical: 8, paddingHorizontal: 14,
    borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)',
  },
  typePillActive: { backgroundColor: 'rgba(0,191,255,0.15)', borderColor: '#00BFFF' },
  typePillText:   { fontFamily: brandFonts.body, fontSize: 13, color: brandColors.mutedText },
  typePillTextActive: { color: '#00BFFF' },
  btn: {
    backgroundColor: '#00BFFF', borderRadius: 10,
    paddingVertical: 16, alignItems: 'center', justifyContent: 'center', minHeight: 52, marginTop: 32,
  },
  btnDisabled: { opacity: 0.85 },
  btnInner: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  btnText: { color: '#000', fontSize: 13, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase' },
  error: { fontFamily: brandFonts.body, fontSize: 13, color: brandColors.alphaRed, marginTop: 12, lineHeight: 18 },
});
