/** Auto-generated by scripts/generate-cheat-sheet-cards.ts — do not edit manually. */
import type { CheatSheetCard } from "../utils/parseToolkitSlideHtml";

export const CHEAT_SHEET_BY_SLIDE_ID: Record<string, CheatSheetCard[]> = {
  "iso-noise": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "ISO & Noise",
      "subheading": "Clean • Controlled • Intentional",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Why It Matters",
      "bullets": [
        "High ISO introduces noise",
        "Noise affects shadows first",
        "ISO should be your last exposure tool"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "ISO vs Noise",
      "bullets": [],
      "steps": [],
      "caption": "Higher ISO = more noise.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "How To Use It",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set aperture and shutter first."
        },
        {
          "label": "STEP 2",
          "text": "Raise ISO only as needed."
        },
        {
          "label": "STEP 3",
          "text": "Expose slightly brighter to reduce noise."
        },
        {
          "label": "STEP 4",
          "text": "Fix minor noise in post."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Expose to the right (ETTR) to minimize noise."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Using ISO as the primary exposure tool."
      },
      "hasDiagram": false
    }
  ],
  "aperture-depth": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "APERTURE & DEPTH OF FIELD",
      "subheading": "Control Focus • Control Style",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Affects background blur",
        "Controls light entering the lens",
        "Shapes the emotional tone of the shot"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "DEPTH OF FIELD",
      "bullets": [],
      "steps": [],
      "caption": "Lower f&#8209;stop = shallower depth.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "HOW TO USE IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Choose f&#8209;stop based on subject."
        },
        {
          "label": "STEP 2",
          "text": "Adjust shutter to maintain exposure."
        },
        {
          "label": "STEP 3",
          "text": "Raise ISO only if needed."
        },
        {
          "label": "STEP 4",
          "text": "Check focus carefully."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use f/2.8 or lower for cinematic separation."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Shooting wide open without checking focus."
      },
      "hasDiagram": false
    }
  ],
  "shutter-motion": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Shutter Speed & Motion",
      "subheading": "Freeze • Blur • Stylize",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Why It Matters",
      "bullets": [
        "Controls motion blur",
        "Affects realism and style",
        "Impacts exposure"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Motion Blur Levels",
      "bullets": [],
      "steps": [],
      "caption": "Faster shutter = less blur.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "How To Use It",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set shutter to double your frame rate."
        },
        {
          "label": "STEP 2",
          "text": "Increase shutter for action."
        },
        {
          "label": "STEP 3",
          "text": "Lower shutter for stylized blur."
        },
        {
          "label": "STEP 4",
          "text": "Rebalance exposure."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use high shutter speeds for crisp sports footage."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Using fast shutter indoors and underexposing."
      },
      "hasDiagram": false
    }
  ],
  "exposure-triangle": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Exposure Triangle",
      "subheading": "Aperture • Shutter • ISO",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Why It Matters",
      "bullets": [
        "Controls brightness and creative style",
        "Each setting affects the others",
        "Mastery gives full control over your image"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Triangle Relationship",
      "bullets": [],
      "steps": [],
      "caption": "Aperture, shutter speed, and ISO work together.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "How To Balance",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set aperture for depth of field."
        },
        {
          "label": "STEP 2",
          "text": "Set shutter speed for motion."
        },
        {
          "label": "STEP 3",
          "text": "Raise ISO only when needed."
        },
        {
          "label": "STEP 4",
          "text": "Rebalance all three for proper exposure."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Lock two settings for your style and adjust the third."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA BASICS",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Using ISO as the primary exposure tool."
      },
      "hasDiagram": false
    }
  ],
  "manual-mode": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Manual Mode",
      "subheading": "You control all three exposure variables — nothing changes unless you change it.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Why It Matters",
      "bullets": [
        "Manual Mode gives you full control over exposure.",
        "It matters because nothing shifts automatically — your creative intent stays locked.",
        "You set aperture, shutter speed, and ISO yourself."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "You set aperture, shutter speed, and ISO yourself.",
      "hasDiagram": true
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set aperture for depth of field."
        },
        {
          "label": "STEP 2",
          "text": "Set shutter for motion."
        },
        {
          "label": "STEP 3",
          "text": "Raise ISO only as needed."
        },
        {
          "label": "STEP 4",
          "text": "Rebalance exposure until histogram is centered."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Lock two settings for your style and adjust the third for exposure."
      },
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Forgetting ISO is still part of the triangle and letting it drift too high."
      },
      "hasDiagram": false
    }
  ],
  "aperture-priority": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Aperture Priority",
      "subheading": "You control depth — the camera controls motion.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Why It Matters",
      "bullets": [
        "Aperture Priority lets you control depth of field while the camera sets shutter speed automatically.",
        "You choose the f‑stop; the camera adjusts shutter to maintain exposure.",
        "You control depth — the camera controls motion."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "You choose the f‑stop; the camera adjusts shutter to maintain exposure.",
      "hasDiagram": true
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set your desired f‑stop."
        },
        {
          "label": "STEP 2",
          "text": "Watch shutter speed to avoid motion blur."
        },
        {
          "label": "STEP 3",
          "text": "Adjust exposure compensation if needed."
        },
        {
          "label": "STEP 4",
          "text": "Keep ISO low for clean images."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use Aperture Priority when lighting changes quickly but depth must stay consistent."
      },
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Letting shutter drop too low and introducing motion blur."
      },
      "hasDiagram": false
    }
  ],
  "shutter-priority": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Shutter Priority",
      "subheading": "You control motion — the camera controls depth.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Why It Matters",
      "bullets": [
        "Shutter Priority locks motion style while the camera adjusts aperture.",
        "You choose shutter speed; the camera sets aperture.",
        "You control motion — the camera controls depth."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "You choose shutter speed; the camera sets aperture.",
      "hasDiagram": true
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set shutter based on motion needs."
        },
        {
          "label": "STEP 2",
          "text": "Monitor aperture to avoid underexposure."
        },
        {
          "label": "STEP 3",
          "text": "Raise ISO if aperture maxes out."
        },
        {
          "label": "STEP 4",
          "text": "Use exposure compensation to fine‑tune."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use Shutter Priority for fast-moving subjects outdoors."
      },
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Forgetting aperture may hit its limit and cause underexposure."
      },
      "hasDiagram": false
    }
  ],
  "picture-profiles": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Picture Profiles",
      "subheading": "Choose profiles based on grading needs — not habit.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Why It Matters",
      "bullets": [
        "Picture profiles define the look of your footage in‑camera.",
        "They matter because they affect contrast, color, and dynamic range.",
        "Standard profiles look finished but limit grading."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Standard profiles look finished but limit grading.",
      "hasDiagram": true
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Pick Standard for fast delivery."
        },
        {
          "label": "STEP 2",
          "text": "Pick Log for cinematic grading."
        },
        {
          "label": "STEP 3",
          "text": "Use monitoring LUTs for Log."
        },
        {
          "label": "STEP 4",
          "text": "Expose Log brighter to avoid noise."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use Log only when you plan to grade intentionally."
      },
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Underexposing Log and creating noisy shadows."
      },
      "hasDiagram": false
    }
  ],
  "raw-vs-compressed": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "RAW vs Compressed",
      "subheading": "Use RAW for maximum control — compressed for speed.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Why It Matters",
      "bullets": [
        "RAW captures maximum sensor data; compressed formats save space.",
        "It matters because workflow and storage change dramatically.",
        "RAW gives flexibility but requires heavy processing."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "RAW gives flexibility but requires heavy processing.",
      "hasDiagram": true
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Use RAW for high-end or cinematic work."
        },
        {
          "label": "STEP 2",
          "text": "Use compressed for social content or fast edits."
        },
        {
          "label": "STEP 3",
          "text": "Ensure storage can handle RAW."
        },
        {
          "label": "STEP 4",
          "text": "Match codec to your editing machine."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "ProRes RAW or BRAW offer a strong balance of flexibility and workflow."
      },
      "hasDiagram": false
    },
    {
      "topic": "SHOOTING MODES",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Overshooting RAW without enough storage or processing power."
      },
      "hasDiagram": false
    }
  ],
  "handheld": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Handheld",
      "subheading": "Stability first — movement second.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Why It Matters",
      "bullets": [
        "Handheld shooting adds energy and realism.",
        "It matters because it creates an immersive, human feel.",
        "Use controlled micro-movements, stable posture, and intentional motion."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Use controlled micro-movements, stable posture, and intentional motion.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Tuck elbows in."
        },
        {
          "label": "STEP 2",
          "text": "Use your body as a shock absorber."
        },
        {
          "label": "STEP 3",
          "text": "Move intentionally, not randomly."
        },
        {
          "label": "STEP 4",
          "text": "Add subtle motion to avoid static shake."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use a wider lens to hide micro‑shake."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Over‑shaking the camera and calling it &quot;handheld style.&quot;"
      },
      "hasDiagram": false
    }
  ],
  "gimbal": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Gimbal",
      "subheading": "Smooth steps = smooth footage.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Why It Matters",
      "bullets": [
        "Gimbals create smooth, floating movement.",
        "They matter because they add polish and cinematic motion.",
        "Balance the camera, walk heel‑to‑toe, and keep movements slow and intentional."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Balance the camera, walk heel‑to‑toe, and keep movements slow and intentional.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Balance the gimbal perfectly."
        },
        {
          "label": "STEP 2",
          "text": "Use slow, controlled movements."
        },
        {
          "label": "STEP 3",
          "text": "Keep horizon level."
        },
        {
          "label": "STEP 4",
          "text": "Avoid sudden pans or tilts."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use &quot;follow&quot; mode for natural movement and &quot;lock&quot; mode for precision."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Running with a gimbal and creating bounce."
      },
      "hasDiagram": false
    }
  ],
  "static-locked": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Static",
      "subheading": "If the camera doesn't move, the composition must be perfect.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Why It Matters",
      "bullets": [
        "Locked-off shots create stability and focus.",
        "They matter because they feel intentional and professional.",
        "Use a tripod or solid surface."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Use a tripod or solid surface.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Level the tripod."
        },
        {
          "label": "STEP 2",
          "text": "Frame with purpose."
        },
        {
          "label": "STEP 3",
          "text": "Lock all adjustments."
        },
        {
          "label": "STEP 4",
          "text": "Avoid touching the camera during takes."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use static shots to contrast dynamic sequences."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Crooked horizons or sloppy framing."
      },
      "hasDiagram": false
    }
  ],
  "dolly-slider": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Dolly / Slider",
      "subheading": "Movement must serve the story — not distract.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Why It Matters",
      "bullets": [
        "Dolly and slider moves add controlled, cinematic motion.",
        "They matter because they feel intentional and smooth.",
        "Use slow, consistent movement."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Use slow, consistent movement.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Set a slow, steady pace."
        },
        {
          "label": "STEP 2",
          "text": "Keep subject distance consistent."
        },
        {
          "label": "STEP 3",
          "text": "Use foreground elements for parallax."
        },
        {
          "label": "STEP 4",
          "text": "Avoid speed changes mid‑move."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use sliders for micro‑moves that elevate simple shots."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Moving too fast and losing cinematic feel."
      },
      "hasDiagram": false
    }
  ],
  "camera-whip-pan": [
    {
      "topic": "AVA CREATORS TOOLKIT · CAMERA",
      "heading": "Whip Pan",
      "subheading": "Motion blur hides the cut.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Why It Matters",
      "bullets": [
        "Whip pans create fast, energetic transitions.",
        "They matter because they add momentum and hide cuts.",
        "Start and end with a fast horizontal motion."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Visual Guide",
      "bullets": [],
      "steps": [],
      "caption": "Start and end with a fast horizontal motion.",
      "hasDiagram": true
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "How To",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Start with a clean frame."
        },
        {
          "label": "STEP 2",
          "text": "Whip quickly left or right."
        },
        {
          "label": "STEP 3",
          "text": "Match the direction on the next shot."
        },
        {
          "label": "STEP 4",
          "text": "Cut at peak blur."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Pro Tip",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Shoot at a higher shutter speed to keep the blur clean."
      },
      "hasDiagram": false
    },
    {
      "topic": "CAMERA MOVEMENT",
      "heading": "Common Mistake",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Whipping too slowly and revealing the cut."
      },
      "hasDiagram": false
    }
  ],
  "rule-of-thirds": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "RULE OF THIRDS",
      "subheading": "Place your subject on a third, not the center, unless you have a reason.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "The rule of thirds divides your frame into a 3×3 grid for natural balance.",
        "Placing eyes, horizons, or key objects on the intersections creates tension and interest.",
        "Use the opposite third for negative space to guide the viewer's eye."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "THIRDS GRID",
      "bullets": [],
      "steps": [],
      "caption": "Place eyes and key elements on grid intersections—not dead center by habit.",
      "hasDiagram": true
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Turn on your camera's grid."
        },
        {
          "label": "STEP 2",
          "text": "Place the subject on a vertical third."
        },
        {
          "label": "STEP 3",
          "text": "Place eyes on a horizontal third."
        },
        {
          "label": "STEP 4",
          "text": "Break the rule only with intention."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use the opposite third for negative space to create direction."
      },
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Centering everything out of habit."
      },
      "hasDiagram": false
    }
  ],
  "leading-lines": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "LEADING LINES",
      "subheading": "Use lines to direct attention",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Leading lines guide the viewer's eye through the frame.",
        "They create depth and visual flow.",
        "Especially powerful in wide shots."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "LINE FLOW",
      "bullets": [],
      "steps": [],
      "caption": "Use lines to direct attention, not distract from it.",
      "hasDiagram": true
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Look for natural lines in the environment."
        },
        {
          "label": "STEP 2",
          "text": "Position your subject at the end of the line."
        },
        {
          "label": "STEP 3",
          "text": "Adjust angle to strengthen the line."
        },
        {
          "label": "STEP 4",
          "text": "Keep lines clean—avoid clutter."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Diagonal lines add more energy than horizontal ones."
      },
      "hasDiagram": false
    },
    {
      "topic": "FOUNDATIONAL RULES",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Letting lines lead out of the frame instead of toward the subject."
      },
      "hasDiagram": false
    }
  ],
  "depth": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "DEPTH LAYERS",
      "subheading": "Always build at least three layers in your frame.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Depth layers create dimensionality—they matter because flat images feel cheap and lifeless.",
        "Foreground adds texture, midground holds the subject, background sets context.",
        "Move your camera, not just your zoom, to build layers."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "THREE LAYERS",
      "bullets": [],
      "steps": [],
      "caption": "Foreground, midground, and background separate your subject from a flat frame.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "HOW TO BUILD LAYERS",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Add a foreground element."
        },
        {
          "label": "STEP 2",
          "text": "Place your subject in the midground."
        },
        {
          "label": "STEP 3",
          "text": "Use background to set context."
        },
        {
          "label": "STEP 4",
          "text": "Adjust aperture to control separation."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Foreground blur instantly adds production value."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Shooting everything from eye level with no layers."
      },
      "hasDiagram": false
    }
  ],
  "camera-angles": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "HIGH ANGLE VS LOW ANGLE",
      "subheading": "Choose angle based on the character's emotional state.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "High angles diminish subjects; low angles empower them—angle changes meaning.",
        "A high angle makes a subject look small, vulnerable, or overwhelmed.",
        "A low angle makes them look strong, dominant, or heroic."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "ANGLE MEANING",
      "bullets": [],
      "steps": [],
      "caption": "Raise or lower the camera to reinforce power, vulnerability, or neutrality.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "HOW TO CHOOSE ANGLE",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Decide what the scene says about the subject."
        },
        {
          "label": "STEP 2",
          "text": "Raise or lower the camera accordingly."
        },
        {
          "label": "STEP 3",
          "text": "Keep vertical lines straight."
        },
        {
          "label": "STEP 4",
          "text": "Rebalance composition after changing angle."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Low angles with wide lenses exaggerate power."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Using eye level for every shot."
      },
      "hasDiagram": false
    }
  ],
  "headroom-lookroom": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "HEADROOM & LOOK ROOM",
      "subheading": "Give subjects space in the direction they're looking",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Headroom and nose room control breathing space around a subject.",
        "Too much headroom feels amateur; too little feels cramped.",
        "Small adjustments make big differences."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "FRAMING SPACE",
      "bullets": [],
      "steps": [],
      "caption": "Give subjects space in the direction they're looking.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Place eyes on the upper third."
        },
        {
          "label": "STEP 2",
          "text": "Leave space in front of the face."
        },
        {
          "label": "STEP 3",
          "text": "Adjust headroom based on emotion."
        },
        {
          "label": "STEP 4",
          "text": "Reframe after movement."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Less nose room creates tension—use intentionally."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Centering the head vertically."
      },
      "hasDiagram": false
    }
  ],
  "vertical-composition": [
    {
      "topic": "AVA CREATORS TOOLKIT · FRAMING",
      "heading": "VERTICAL COMPOSITION",
      "subheading": "Compose for 9:16 delivery from day one",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Shooting 16:9 but delivering 9:16 requires planning the crop.",
        "Place subjects on the center third—never the edges.",
        "Vertical safe area keeps faces and text visible on mobile."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "9:16 SAFE AREA",
      "bullets": [],
      "steps": [],
      "caption": "Native vertical beats stretched horizontal.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Enable vertical safe-area guides on monitor or app."
        },
        {
          "label": "STEP 2",
          "text": "Place subject on center third for 9:16 crop."
        },
        {
          "label": "STEP 3",
          "text": "Keep faces and titles inside the safe zone."
        },
        {
          "label": "STEP 4",
          "text": "Shoot native vertical when the platform is vertical-first."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Frame for the crop before you roll—fixing in post costs resolution."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED COMPOSITION",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Placing subjects on the edge of a horizontal frame you plan to crop."
      },
      "hasDiagram": false
    }
  ],
  "three-point-lighting": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "THREE-POINT LIGHTING",
      "subheading": "Key, Fill, Backlight",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Defines subject shape and depth",
        "Separates subject from background",
        "Works for interviews, portraits, and narrative"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "BASIC LAYOUT",
      "bullets": [],
      "steps": [],
      "caption": "Key at 45°, fill opposite, backlight behind subject.",
      "hasDiagram": true
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "HOW TO SET IT UP",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Place key light at a 45° angle to the subject."
        },
        {
          "label": "STEP 2",
          "text": "Add fill on the opposite side to control contrast."
        },
        {
          "label": "STEP 3",
          "text": "Add backlight behind the subject for separation."
        },
        {
          "label": "STEP 4",
          "text": "Adjust intensities to match the mood."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use negative fill instead of more lights when you want drama."
      },
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Over-filling and flattening the face."
      },
      "hasDiagram": false
    }
  ],
  "hard-soft-light": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "HARD VS SOFT LIGHT",
      "subheading": "Bigger source = softer light",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Hard light creates sharp shadows; soft light creates smooth transitions",
        "Hard light adds drama and texture; soft light flatters faces",
        "Control hardness by changing source size or distance"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "SOURCE SIZE",
      "bullets": [],
      "steps": [],
      "caption": "Small direct source = hard; large diffused source = soft.",
      "hasDiagram": true
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "HOW TO CONTROL IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Move light closer for softness."
        },
        {
          "label": "STEP 2",
          "text": "Add diffusion for smoother shadows."
        },
        {
          "label": "STEP 3",
          "text": "Use bare bulbs or fresnels for hard light."
        },
        {
          "label": "STEP 4",
          "text": "Shape shadows with flags."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Soft light still needs direction—don't flatten it."
      },
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Confusing soft light with low‑contrast lighting."
      },
      "hasDiagram": false
    }
  ],
  "color-temperature": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "COLOR TEMPERATURE",
      "subheading": "Match all lights to one color temperature",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Color temperature defines the warmth or coolness of light",
        "Mixed temperatures ruin skin tones",
        "Consistent color temperature makes grading easier and cleaner"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "KELVIN SCALE",
      "bullets": [],
      "steps": [],
      "caption": "Daylight ~5600K; tungsten ~3200K — match your lights to the dominant source.",
      "hasDiagram": true
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "HOW TO MATCH",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Identify the dominant light source."
        },
        {
          "label": "STEP 2",
          "text": "Set camera white balance to match."
        },
        {
          "label": "STEP 3",
          "text": "Gel lights to match the environment."
        },
        {
          "label": "STEP 4",
          "text": "Avoid mixing warm and cool sources."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use warm light for intimacy and cool light for tension."
      },
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING BASICS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Ignoring practical lights that contaminate the scene."
      },
      "hasDiagram": false
    }
  ],
  "interview-setup": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "INTERVIEW SETUP",
      "subheading": "Light the subject brighter than the background.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Interview lighting prioritizes clarity and flattering skin—interviews are unforgiving.",
        "Use a soft key at 45°, a gentle fill, and a subtle backlight.",
        "Keep the background slightly darker than the subject."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "INTERVIEW LAYOUT",
      "bullets": [],
      "steps": [],
      "caption": "Soft key at 45°, fill to taste, backlight for separation, practicals for depth.",
      "hasDiagram": true
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "HOW TO LIGHT IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Place soft key at 45°."
        },
        {
          "label": "STEP 2",
          "text": "Add fill to taste."
        },
        {
          "label": "STEP 3",
          "text": "Add backlight for separation."
        },
        {
          "label": "STEP 4",
          "text": "Shape background with practicals."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use negative fill on the far side for dimension."
      },
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Lighting the background brighter than the subject."
      },
      "hasDiagram": false
    }
  ],
  "cinematic-setup": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "CINEMATIC SETUP",
      "subheading": "Light with motivation, not symmetry",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Cinematic lighting uses contrast, direction, and color to create mood",
        "Use motivated light sources—windows, lamps, screens",
        "Cinematic lighting is about intention, not brightness"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "MOTIVATED LAYOUT",
      "bullets": [],
      "steps": [],
      "caption": "Motivated key, negative fill for depth, warm vs cool separation.",
      "hasDiagram": true
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "HOW TO BUILD IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Choose a motivated key source."
        },
        {
          "label": "STEP 2",
          "text": "Add negative fill for contrast."
        },
        {
          "label": "STEP 3",
          "text": "Add backlight or edge light."
        },
        {
          "label": "STEP 4",
          "text": "Add color contrast subtly."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Turn off overheads—they kill cinematic mood."
      },
      "hasDiagram": false
    },
    {
      "topic": "LIGHTING SETUPS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Over‑lighting and losing direction."
      },
      "hasDiagram": false
    }
  ],
  "rembrandt-lighting": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "REMBRANDT LIGHTING",
      "subheading": "Aim for the signature triangle under the eye",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Rembrandt lighting creates a triangle of light under the eye",
        "It adds depth and drama",
        "Works well for portraits and interviews"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "THE TRIANGLE",
      "bullets": [],
      "steps": [],
      "caption": "Key at 45° above eye level — nose shadow connects to cheek, leaving a lit triangle.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "HOW TO SET IT UP",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Place key at 45°."
        },
        {
          "label": "STEP 2",
          "text": "Raise it slightly above eye level."
        },
        {
          "label": "STEP 3",
          "text": "Adjust angle until triangle forms."
        },
        {
          "label": "STEP 4",
          "text": "Add fill sparingly."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use negative fill to deepen the shadow side."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Letting the triangle get too large or too bright."
      },
      "hasDiagram": false
    }
  ],
  "practical-motivated": [
    {
      "topic": "AVA CREATORS TOOLKIT · LIGHTING",
      "heading": "PRACTICAL MOTIVATED LIGHT",
      "subheading": "Let practicals dictate your lighting direction",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Motivated lighting uses practicals as the source of your key",
        "It grounds your lighting in reality",
        "Motivated lighting blends realism with control"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "PRACTICAL + HIDDEN KEY",
      "bullets": [],
      "steps": [],
      "caption": "Key feels like it comes from the practical — hidden lights boost the same direction.",
      "hasDiagram": true
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "HOW TO BUILD IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Identify the practical source."
        },
        {
          "label": "STEP 2",
          "text": "Place key in the same direction."
        },
        {
          "label": "STEP 3",
          "text": "Boost practical with hidden lights."
        },
        {
          "label": "STEP 4",
          "text": "Match color temperature."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Dim practicals to avoid clipping while keeping ambiance."
      },
      "hasDiagram": false
    },
    {
      "topic": "ADVANCED LIGHTING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Lighting from a direction that contradicts the practical."
      },
      "hasDiagram": false
    }
  ],
  "interface-overview": [
    {
      "topic": "AVA CREATORS TOOLKIT · DAVINCI RESOLVE",
      "heading": "INTERFACE OVERVIEW",
      "subheading": "Use each page for its intended purpose.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "GETTING STARTED",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "DaVinci Resolve is divided into specialized pages.",
        "Each page handles a different part of the workflow.",
        "Cut is for fast edits.",
        "Edit is for detailed timeline work."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "GETTING STARTED",
      "heading": "RESOLVE PAGES",
      "bullets": [],
      "steps": [],
      "caption": "Fusion handles VFX. Color is for grading. Fairlight is for audio. Deliver exports your final project.",
      "hasDiagram": true
    },
    {
      "topic": "GETTING STARTED",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Open project and navigate pages."
        },
        {
          "label": "STEP 2",
          "text": "Use Cut for quick assembly."
        },
        {
          "label": "STEP 3",
          "text": "Use Edit for precision."
        },
        {
          "label": "STEP 4",
          "text": "Use Color and Fairlight for finishing."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "GETTING STARTED",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Keyboard shortcuts differ by page—learn them."
      },
      "hasDiagram": false
    },
    {
      "topic": "GETTING STARTED",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Trying to do everything on the Edit page."
      },
      "hasDiagram": false
    }
  ],
  "color-wheels": [
    {
      "topic": "AVA CREATORS TOOLKIT · COLOR GRADING",
      "heading": "COLOR WHEELS",
      "subheading": "Lift, Gamma, Gain",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Lift, Gamma, and Gain control shadows, midtones, and highlights.",
        "They shape the entire tonal balance.",
        "Lift adjusts shadows.",
        "Gamma adjusts midtones."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "LIFT · GAMMA · GAIN",
      "bullets": [],
      "steps": [],
      "caption": "Gain adjusts highlights. Use small adjustments to avoid breaking the image.",
      "hasDiagram": true
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Balance exposure with Lift/Gamma/Gain."
        },
        {
          "label": "STEP 2",
          "text": "Adjust color balance."
        },
        {
          "label": "STEP 3",
          "text": "Add contrast."
        },
        {
          "label": "STEP 4",
          "text": "Refine skin tones."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use scopes, not your eyes alone."
      },
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Crushing shadows too early."
      },
      "hasDiagram": false
    }
  ],
  "curves": [
    {
      "topic": "AVA CREATORS TOOLKIT · COLOR GRADING",
      "heading": "CURVES",
      "subheading": "RGB and Luma",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Curves give precise control over contrast and color.",
        "They allow fine‑tuning.",
        "Use the luma curve for contrast.",
        "Use RGB curves for color shifts."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "LUMA + RGB",
      "bullets": [],
      "steps": [],
      "caption": "Use curves to refine, not replace, basic grading.",
      "hasDiagram": true
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Add anchor points."
        },
        {
          "label": "STEP 2",
          "text": "Adjust luma for contrast."
        },
        {
          "label": "STEP 3",
          "text": "Use RGB for color shifts."
        },
        {
          "label": "STEP 4",
          "text": "Check scopes."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "S‑curves add cinematic contrast."
      },
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Over‑bending curves and creating artifacts."
      },
      "hasDiagram": false
    }
  ],
  "skin-tone-correction": [
    {
      "topic": "AVA CREATORS TOOLKIT · COLOR GRADING",
      "heading": "SKIN TONE CORRECTION",
      "subheading": "Natural, Consistent, Believable",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SKIN TONE CORRECTION",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Viewers judge skin instantly",
        "Bad skin tones break trust",
        "Good skin tones survive platform compression"
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "SKIN TONE CORRECTION",
      "heading": "VECTORSCOPE SKIN LINE",
      "bullets": [],
      "steps": [],
      "caption": "Keep skin values aligned with the skin tone line.",
      "hasDiagram": true
    },
    {
      "topic": "SKIN TONE CORRECTION",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Open the vectorscope and isolate the skin region."
        },
        {
          "label": "STEP 2",
          "text": "Balance exposure before touching color."
        },
        {
          "label": "STEP 3",
          "text": "Adjust hue and saturation in small increments."
        },
        {
          "label": "STEP 4",
          "text": "Use qualifiers only when global adjustments fail."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "SKIN TONE CORRECTION",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Check skin under multiple lighting angles—grading for one angle can break another."
      },
      "hasDiagram": false
    },
    {
      "topic": "SKIN TONE CORRECTION",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Oversaturating skin to 'make it pop'."
      },
      "hasDiagram": false
    }
  ],
  "scopes": [
    {
      "topic": "AVA CREATORS TOOLKIT · COLOR GRADING",
      "heading": "READING SCOPES",
      "subheading": "Waveforms & Vectorscope",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Waveforms and scopes show the truth about your image.",
        "Monitors lie.",
        "The waveform reads luminance.",
        "The RGB parade shows color balance."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "SCOPE LAYOUT",
      "bullets": [],
      "steps": [],
      "caption": "The vectorscope shows hue and saturation—especially the skin tone line on the yellow-red axis.",
      "hasDiagram": true
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Read the waveform for exposure—skin sits ~50–70 IRE on Rec.709."
        },
        {
          "label": "STEP 2",
          "text": "Check the parade for RGB balance on neutrals."
        },
        {
          "label": "STEP 3",
          "text": "Use the vectorscope—keep skin on the skin tone line."
        },
        {
          "label": "STEP 4",
          "text": "Calibrate your monitor annually—scopes do not lie."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Histogram alone lies on LOG—use the waveform for exposure."
      },
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Grading by eye on an uncalibrated display."
      },
      "hasDiagram": false
    }
  ],
  "node-structure": [
    {
      "topic": "AVA CREATORS TOOLKIT · COLOR GRADING",
      "heading": "NODE STRUCTURE",
      "subheading": "Serial, Parallel, Layer",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Node structure organizes your grade into repeatable steps.",
        "Messy node trees break consistency.",
        "Serial nodes stack in order.",
        "Parallel nodes split the image."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "NODE TREE",
      "bullets": [],
      "steps": [],
      "caption": "Layer nodes combine passes. Build prep → look → skin → background so changes stay isolated.",
      "hasDiagram": true
    },
    {
      "topic": "COLOR GRADING",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Input transform and exposure normalize."
        },
        {
          "label": "STEP 2",
          "text": "Spatial NR and exposure zones if needed."
        },
        {
          "label": "STEP 3",
          "text": "Creative look node."
        },
        {
          "label": "STEP 4",
          "text": "Dedicated skin and background nodes."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Export node stills for match reference on long projects."
      },
      "hasDiagram": false
    },
    {
      "topic": "COLOR GRADING",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "One giant node that does everything."
      },
      "hasDiagram": false
    }
  ],
  "whip-pan": [
    {
      "topic": "AVA CREATORS TOOLKIT · TRANSITIONS",
      "heading": "WHIP PAN TRANSITION",
      "subheading": "Match direction and speed—or the cut feels accidental.",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "TRANSITIONS & EFFECTS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "A whip pan transition connects scenes with blur and energy.",
        "Motion hides the cut.",
        "Shoot whip out and whip in at the same speed and direction on set.",
        "Cut at peak blur—neither frame should be sharp at the edit point."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "TRANSITIONS & EFFECTS",
      "heading": "CUT AT PEAK BLUR",
      "bullets": [],
      "steps": [],
      "caption": "In post, directional blur 2–4 frames each side can fake the move.",
      "hasDiagram": true
    },
    {
      "topic": "TRANSITIONS & EFFECTS",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Shoot whip out and whip in on set."
        },
        {
          "label": "STEP 2",
          "text": "Cut at peak blur on both sides."
        },
        {
          "label": "STEP 3",
          "text": "Add directional blur in post if needed."
        },
        {
          "label": "STEP 4",
          "text": "Sync to whoosh SFX or a music hit."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "TRANSITIONS & EFFECTS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Plan the exit and entry framing before the first whip."
      },
      "hasDiagram": false
    },
    {
      "topic": "TRANSITIONS & EFFECTS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Mixing whip directions in the same sequence."
      },
      "hasDiagram": false
    }
  ],
  "fairlight-basics": [
    {
      "topic": "AVA CREATORS TOOLKIT · AUDIO",
      "heading": "FAIRLIGHT BASICS",
      "subheading": "EQ, Compression, Levels",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Fairlight is Resolve's audio page for mix and delivery.",
        "Bad audio kills good footage.",
        "Normalize dialogue to -18 to -14 LUFS integrated for web.",
        "High-pass at 80–100Hz on lavs to remove rumble."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "DIALOGUE CHAIN",
      "bullets": [],
      "steps": [],
      "caption": "Dialogue clarity beats loud music every time.",
      "hasDiagram": true
    },
    {
      "topic": "AUDIO",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Normalize dialogue to web LUFS targets."
        },
        {
          "label": "STEP 2",
          "text": "High-pass lavs at 80–100Hz."
        },
        {
          "label": "STEP 3",
          "text": "Apply light compression on dialogue."
        },
        {
          "label": "STEP 4",
          "text": "Limit the master bus to -1dB true peak."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Mix with monitors at conversation level—not blasted."
      },
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Over-compressing dialogue until it sounds robotic."
      },
      "hasDiagram": false
    }
  ],
  "dialogue-cleanup": [
    {
      "topic": "AVA CREATORS TOOLKIT · AUDIO",
      "heading": "DIALOGUE CLEANUP",
      "subheading": "Noise Reduction",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Dialogue cleanup fixes location audio before anyone else hears it.",
        "Noise reduction is not optional on client work.",
        "Learn a noise profile from a room-tone snippet in RX or Fairlight.",
        "De-plosive and de-ess lightly—over-processing sounds robotic."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "NOISE PROFILE",
      "bullets": [],
      "steps": [],
      "caption": "Fix dialogue before you mix music.",
      "hasDiagram": true
    },
    {
      "topic": "AUDIO",
      "heading": "WORKFLOW",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Learn noise profile from room tone."
        },
        {
          "label": "STEP 2",
          "text": "De-plosive and de-ess lightly."
        },
        {
          "label": "STEP 3",
          "text": "Cut distracting breaths by hand."
        },
        {
          "label": "STEP 4",
          "text": "Keep unprocessed backups on muted tracks."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Process a short section first—ears fatigue on long passes."
      },
      "hasDiagram": false
    },
    {
      "topic": "AUDIO",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Heavy NR that turns voices into underwater radio."
      },
      "hasDiagram": false
    }
  ],
  "instagram-reels": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "INSTAGRAM REELS",
      "subheading": "Hook, Pacing, Caption Strategy",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Hook in frame one—face, action, or bold text before the swipe.",
        "Shoot native 9:16 in camera, not stretched in post.",
        "Burn captions on-screen—most viewers watch muted."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "REELS FRAME FLOW",
      "bullets": [],
      "steps": [],
      "caption": "Win the first 1.5 seconds or lose the viewer.",
      "hasDiagram": true
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Open with a visual hook in frame one."
        },
        {
          "label": "STEP 2",
          "text": "Shoot native 9:16 vertical."
        },
        {
          "label": "STEP 3",
          "text": "Add on-screen captions for muted viewing."
        },
        {
          "label": "STEP 4",
          "text": "Post when insights show your audience is active."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Motion in the opening frame beats a static title card."
      },
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Stretching 16:9 into vertical instead of reframing."
      },
      "hasDiagram": false
    }
  ],
  "tiktok-native": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "TIKTOK NATIVE",
      "subheading": "Native Feel, Trending Audio, Retention",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Shoot lo-fi when the brand allows—polished reads as an ad.",
        "Match the end frame to the start for seamless loops—the algorithm rewards rewatches.",
        "Use trending audio inside your niche quickly—stale trends hurt reach."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "LOOP + RETENTION",
      "bullets": [],
      "steps": [],
      "caption": "Native feel beats polished unless the brand demands polish.",
      "hasDiagram": true
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Match end frame to start for loops."
        },
        {
          "label": "STEP 2",
          "text": "Use trending audio while it is still fresh."
        },
        {
          "label": "STEP 3",
          "text": "Reply to comments with video."
        },
        {
          "label": "STEP 4",
          "text": "State the payoff in the first 0.5 seconds."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Lo-fi BTS often outperforms glossy hero edits on TikTok."
      },
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Recycling Instagram polish without adapting pacing."
      },
      "hasDiagram": false
    }
  ],
  "youtube-titles-thumbs": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "YOUTUBE TITLES & THUMBS",
      "subheading": "Titles, Thumbnails, Retention Arc",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Deliver the title promise in the first thirty seconds.",
        "Pattern interrupt every thirty to forty-five seconds—B-roll, graphics, angle changes.",
        "Add chapters on videos over eight minutes for session time and snippets."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "CTR + RETENTION ARC",
      "bullets": [],
      "steps": [],
      "caption": "Thumbnail and title must promise what the video delivers.",
      "hasDiagram": true
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Deliver the title promise in the first 30 seconds."
        },
        {
          "label": "STEP 2",
          "text": "Pattern interrupt every 30–45 seconds."
        },
        {
          "label": "STEP 3",
          "text": "Add chapters on 8+ minute videos."
        },
        {
          "label": "STEP 4",
          "text": "A/B test thumbnails before a wide push."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Design the thumbnail before you write the script."
      },
      "hasDiagram": false
    },
    {
      "topic": "PLATFORM MASTERY",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Clickbait titles with slow payoffs—retention collapses."
      },
      "hasDiagram": false
    }
  ],
  "batch-shooting": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "BATCH SHOOTING",
      "subheading": "One Day, 30 Days of Content",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Plan 10–15 scripts or outlines ahead of time.",
        "Shoot all A‑roll in one block.",
        "Capture B‑roll in another."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "BATCH WORKFLOW",
      "bullets": [],
      "steps": [],
      "caption": "Separate planning, shooting, and editing into distinct phases.",
      "hasDiagram": true
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Write 10–15 scripts."
        },
        {
          "label": "STEP 2",
          "text": "Shoot all A‑roll in one session."
        },
        {
          "label": "STEP 3",
          "text": "Capture B‑roll in bulk."
        },
        {
          "label": "STEP 4",
          "text": "Edit in batches."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Use consistent lighting and framing to speed up shooting."
      },
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Trying to plan and shoot on the same day."
      },
      "hasDiagram": false
    }
  ],
  "hook-formula": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "THE HOOK FORMULA",
      "subheading": "First 3 Seconds",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Use problem plus promise in two seconds—the viewer must know why to keep watching.",
        "Show the result first, then rewind to how with a visual hook.",
        "Controversy hooks work sparingly only when you deliver real value."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "FIRST 3 SECONDS",
      "bullets": [],
      "steps": [],
      "caption": "State the payoff before you ask for attention.",
      "hasDiagram": true
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Write problem + promise in text and voice."
        },
        {
          "label": "STEP 2",
          "text": "Show the result first, then rewind."
        },
        {
          "label": "STEP 3",
          "text": "Draft ten hooks—shoot the best two."
        },
        {
          "label": "STEP 4",
          "text": "Open with a face or moving object."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Read the hook out loud—if it sounds like an ad, rewrite it."
      },
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Slow intros that bury the promise after three seconds."
      },
      "hasDiagram": false
    }
  ],
  "repurposing": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "REPURPOSING CONTENT",
      "subheading": "One Video, Five Platforms",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Turn long‑form YouTube videos into shorts, carousels, tweets, and LinkedIn posts.",
        "Extract key insights and repackage them.",
        "Keep platform tone and pacing in mind."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "ONE → FIVE PLATFORMS",
      "bullets": [],
      "steps": [],
      "caption": "Adapt the message to the platform, not the other way around.",
      "hasDiagram": true
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Start with a long‑form anchor video."
        },
        {
          "label": "STEP 2",
          "text": "Pull 5–10 short clips."
        },
        {
          "label": "STEP 3",
          "text": "Convert insights into text posts."
        },
        {
          "label": "STEP 4",
          "text": "Reformat visuals for each platform."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Your best short‑form ideas usually come from long‑form content."
      },
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Posting the same edit everywhere without adapting it."
      },
      "hasDiagram": false
    }
  ],
  "content-pillars": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "CONTENT PILLARS",
      "subheading": "The System That Makes You Consistent",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Choose 3–5 pillars that represent your identity, expertise, and audience needs.",
        "Every piece of content should map to one pillar.",
        "Pillars prevent burnout, eliminate decision fatigue, and keep your message coherent across platforms."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PILLAR GRID",
      "bullets": [],
      "steps": [],
      "caption": "Every post must serve a pillar.",
      "hasDiagram": true
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Define 3–5 core pillars."
        },
        {
          "label": "STEP 2",
          "text": "Map ideas to pillars."
        },
        {
          "label": "STEP 3",
          "text": "Build weekly themes around them."
        },
        {
          "label": "STEP 4",
          "text": "Review and refine monthly."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Your strongest pillar should produce 50% of your content."
      },
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Posting randomly without a strategic framework."
      },
      "hasDiagram": false
    }
  ],
  "hooks-convert": [
    {
      "topic": "AVA CREATORS TOOLKIT · STRATEGY",
      "heading": "HOOKS THAT CONVERT",
      "subheading": "Specific Hook Types That Drive Action",
      "bullets": [],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "WHY IT MATTERS",
      "bullets": [
        "Use problem‑solution hooks to target pain points.",
        "Use &quot;myth‑busting&quot; hooks to challenge assumptions.",
        "Use &quot;here's what nobody tells you&quot; hooks to trigger curiosity."
      ],
      "steps": [],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOOK TYPE → ACTION",
      "bullets": [],
      "steps": [],
      "caption": "Choose hook type based on the action you want the viewer to take.",
      "hasDiagram": true
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "HOW TO APPLY IT",
      "bullets": [],
      "steps": [
        {
          "label": "STEP 1",
          "text": "Identify the desired action."
        },
        {
          "label": "STEP 2",
          "text": "Pick a hook type that aligns with it."
        },
        {
          "label": "STEP 3",
          "text": "Write the hook before filming."
        },
        {
          "label": "STEP 4",
          "text": "Deliver the payoff quickly."
        }
      ],
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "PRO TIP",
      "bullets": [],
      "steps": [],
      "callout": {
        "label": "Pro Tip",
        "text": "Myth‑busting hooks have the highest share rate."
      },
      "hasDiagram": false
    },
    {
      "topic": "CONTENT SYSTEMS",
      "heading": "COMMON MISTAKE",
      "bullets": [],
      "steps": [],
      "warning": {
        "label": "Watch Out",
        "text": "Using hooks that don't match the video's actual value."
      },
      "hasDiagram": false
    }
  ]
} as const;

export const CHEAT_SHEET_SLIDE_IDS = Object.keys(CHEAT_SHEET_BY_SLIDE_ID);

export function getCheatSheetCards(slideId: string): CheatSheetCard[] | undefined {
  return CHEAT_SHEET_BY_SLIDE_ID[slideId];
}
