/**
 * Pre-parse bundled HTML cheat sheets into static TS data (no runtime FileSystem).
 * Run: npx tsx scripts/generate-cheat-sheet-cards.ts
 */
import * as fs from "fs";
import * as path from "path";
import { parseToolkitSlideHtml } from "../utils/parseToolkitSlideHtml";
import { toolkitLessons } from "../data/toolkitCurriculum";

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "data/toolkitCheatSheetCards.ts");

const htmlLessons = toolkitLessons.filter(
  (l) => l.type === "html_presentation" && l.htmlSlidePath && l.htmlSlideId,
);

const bySlideId: Record<string, ReturnType<typeof parseToolkitSlideHtml>> = {};

for (const lesson of htmlLessons) {
  const htmlPath = lesson.htmlSlidePath!;
  const file = path.join(ROOT, "assets/creators-toolkit", htmlPath);
  const html = fs.readFileSync(file, "utf8");
  const cards = parseToolkitSlideHtml(html);
  if (cards.length < 3) {
    console.error("Too few cards for", htmlPath, cards.length);
    process.exit(1);
  }
  bySlideId[lesson.htmlSlideId!] = cards;
}

const body = `/** Auto-generated by scripts/generate-cheat-sheet-cards.ts — do not edit manually. */
import type { CheatSheetCard } from "../utils/parseToolkitSlideHtml";

export const CHEAT_SHEET_BY_SLIDE_ID: Record<string, CheatSheetCard[]> = ${JSON.stringify(bySlideId, null, 2)} as const;

export const CHEAT_SHEET_SLIDE_IDS = Object.keys(CHEAT_SHEET_BY_SLIDE_ID);

export function getCheatSheetCards(slideId: string): CheatSheetCard[] | undefined {
  return CHEAT_SHEET_BY_SLIDE_ID[slideId];
}
`;

fs.writeFileSync(OUT, body);
console.log("Wrote", OUT, "with", Object.keys(bySlideId).length, "cheat sheets");
