-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 007 — pre-submission fixes
-- 1. Public event lookup by QR token (join screen, unauthenticated users)
-- 2. Consent tracking columns on profiles (auth flow)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Allow anyone to look up an event by its QR token.
--    Only the join screen needs this — it shows event name/date before sign-in.
--    Safe: qr_token is a random hex string generated by the DB; it is not
--    guessable. The policy allows SELECT on the row only when qr_token IS NOT
--    NULL (all events have one), so it is effectively an "event exists" check.
drop policy if exists events_public_qr_lookup on public.events;
create policy events_public_qr_lookup on public.events
  for select using (qr_token is not null);

-- 2. Add consent tracking columns to profiles.
--    These are written by consent.tsx after the user accepts ToS / age gate.
--    They did not exist in migrations 001-006 (consent columns were on attendees
--    only). Adding them here unblocks the auth flow for all users.
alter table public.profiles
  add column if not exists tos_accepted_at      timestamptz,
  add column if not exists age_gate_confirmed_at timestamptz,
  add column if not exists marketing_opt_in      boolean not null default false;
